In [1]:
#This file is to import two embeddings and merge them together to generate
# new set of embeddings

import numpy as np

data_location = './../generated_embedding/'
first_embed = open(data_location+'citeseer.edgelist_deepwalk.embeddings','r')
sec_embed = open(data_location+'citeseer.edgelist_struc2vec.embeddings','r')

In [2]:
#loading embedding files from deepwalk and struc2vec embeddings
#assumption embedding length is 128
import numpy as np
import pickle


#Read the first line and get number of nodes in the embedding
temp1 = first_embed.readline()
temp2 = sec_embed.readline()
temp1 = temp1.split()
temp2 = temp2.split()
num_node = int(temp1[0])
len_embed = int(temp1[1])

print("number of nodes %s and length of embedding is %s" % (num_node,len_embed))

new_arr = np.ndarray((num_node,2*len_embed),dtype=float)

#the code here loads each file in a line and then splits into list values.
#First value denotes the node number. That is used to get the index and other values are added to the
#array
for counter in range(num_node):
    temp_embed1 = first_embed.readline().split()
    index_one = int(temp_embed1[0])
    new_arr[index_one,:len_embed]=[float(i) for i in temp_embed1[1:]]
    
    temp_embed2 = sec_embed.readline().split()
    index_two = int(temp_embed2[0])
    new_arr[index_two,len_embed:] = [float(j) for j in temp_embed2[1:]]
    
'''

new_file = open(data_location+"citeseer_combined.embedding",'w')
for i in range(count):
    embed_one = first_embed.readline().split()
    embed_two = sec_embed.readline().split()
    combine = embed_one+embed_two[1:]
    combine = ' '.join(combine)
    new_file.write("%s\n" % combine)

'''
print("finished")

    
first_embed.close()
sec_embed.close()

number of nodes 3327 and length of embedding is 128
finished


In [5]:
#the above function seems to work but hard way to check for accuracy.
#So I will rewrite the code to add two variables and add them later.


def join_embedding(filename1,filename2):
    #loading embedding files from deepwalk and struc2vec embeddings
    #assumption embedding length is 128
    import numpy as np
    import pickle
    data_location = './../generated_embedding/'
    first_embed = open(data_location+filename1,'r')
    sec_embed = open(data_location+filename2,'r')


    #Read the first line and get number of nodes in the embedding
    temp1 = first_embed.readline()
    temp2 = sec_embed.readline()
    temp1 = temp1.split()
    temp2 = temp2.split()
    num_node = int(temp1[0])
    len_embed = int(temp1[1])

    print("number of nodes %s and length of embedding is %s" % (num_node,len_embed))

    temp_arr1 = np.ndarray((num_node,len_embed),dtype=float)
    temp_arr2 = np.ndarray((num_node,len_embed),dtype=float)
    new_arr1 = np.ndarray((num_node,2*len_embed),dtype=float)

    #the code here loads each file in a line and then splits into list values.
    #First value denotes the node number. That is used to get the index and other values are added to the
    #array
    for counter in range(num_node):
        temp_embed1 = first_embed.readline().split()
        index_one = int(temp_embed1[0])
        temp_arr1[index_one,:]=[float(i) for i in temp_embed1[1:]]
    
        temp_embed2 = sec_embed.readline().split()
        index_two = int(temp_embed2[0])
        temp_arr2[index_two,:] = [float(j) for j in temp_embed2[1:]]

    #combining two arrays to get one set of embeddings
    new_arr1[:,:len_embed] = temp_arr1[:,:]
    new_arr1[:,len_embed:] = temp_arr2[:,:]
    
    first_embed.close()
    sec_embed.close()
    print("finished")
    
    return new_arr1


In [ ]:
new_arr

In [3]:
from utils import run_embedding_classify_f1

In [ ]:
run_embedding_classify_f1('citeseer',new_arr,splits_ratio=[0.1, 0.5, 0.9])

In [15]:
#loading deepwalk embeddings for citeseer

f = open(data_location+'citeseer.edgelist_deepwalk.embeddings','r')

firstline = f.readline().split()
emb_node = int(firstline[0])
emb_len = int(firstline[1])

deepwalk_embed = np.ndarray((emb_node,emb_len),dtype=np.float32)

for i in range(emb_node):
    l = f.readline().split()
    t_arr = [float(j) for j in l[1:]]
    emb_index = int(l[0])
    deepwalk_embed[emb_index,:]=t_arr[:]
    
print("finished")
    


finished


In [24]:
 with open(data_location+'citeseer.new_deewalk.embeddings', 'rb') as efile:
        num_node, dim = map(int, efile.readline().split())
        emb_matrix = np.ndarray(shape=(num_node, dim), dtype=np.float32)
        for data in efile.readlines():
            node_id, *vector = data.split()
            node_id = int(node_id)
            emb_matrix[node_id, :] = np.array([i for i in map(np.float, vector)])
  


In [16]:
emb_matrix[0]

array([ 0.094527  , -0.013551  , -0.81741297, -0.095326  ,  0.440483  ,
        0.34503999, -0.204742  , -1.25870502,  0.131451  , -0.31465501,
        0.042019  , -0.056251  , -0.354498  ,  0.450371  , -0.084576  ,
       -0.036903  , -0.405341  , -0.48027301, -0.364216  , -0.200618  ,
        0.057037  ,  0.32684699,  0.26658899, -0.21323501,  0.441268  ,
        0.61049598, -1.75869298,  0.144767  , -0.11791   , -0.018084  ,
        0.0329    ,  0.33786201, -1.47459304, -1.34488201,  0.257934  ,
       -0.432152  , -0.037146  , -0.53013098,  1.30689204, -1.19934404,
       -1.00589502, -0.51819301,  0.355212  , -0.50352502, -0.39936799,
       -0.015843  , -0.72176802,  0.65939599, -0.717305  ,  0.51836199,
        0.91243201, -0.43010101,  0.410236  ,  0.42614701, -0.135993  ,
        0.94635999,  0.238647  ,  0.114305  , -0.18236101,  1.41709602,
        0.077559  , -0.28827199,  0.54010898, -0.97638202,  0.211916  ,
       -0.55612898, -0.61859697,  0.18791699,  0.25792301, -0.19

In [17]:
deepwalk_embed[0]

array([ 0.094527  , -0.013551  , -0.81741297, -0.095326  ,  0.440483  ,
        0.34503999, -0.204742  , -1.25870502,  0.131451  , -0.31465501,
        0.042019  , -0.056251  , -0.354498  ,  0.450371  , -0.084576  ,
       -0.036903  , -0.405341  , -0.48027301, -0.364216  , -0.200618  ,
        0.057037  ,  0.32684699,  0.26658899, -0.21323501,  0.441268  ,
        0.61049598, -1.75869298,  0.144767  , -0.11791   , -0.018084  ,
        0.0329    ,  0.33786201, -1.47459304, -1.34488201,  0.257934  ,
       -0.432152  , -0.037146  , -0.53013098,  1.30689204, -1.19934404,
       -1.00589502, -0.51819301,  0.355212  , -0.50352502, -0.39936799,
       -0.015843  , -0.72176802,  0.65939599, -0.717305  ,  0.51836199,
        0.91243201, -0.43010101,  0.410236  ,  0.42614701, -0.135993  ,
        0.94635999,  0.238647  ,  0.114305  , -0.18236101,  1.41709602,
        0.077559  , -0.28827199,  0.54010898, -0.97638202,  0.211916  ,
       -0.55612898, -0.61859697,  0.18791699,  0.25792301, -0.19

In [18]:
np.equal(deepwalk_embed[0],emb_matrix[0])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True]

In [25]:
run_embedding_classify_f1('citeseer',emb_matrix,splits_ratio=[0.1, 0.5, 0.9])

./../data/


/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricW

Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.618618618619
macro: 0.478295367306
samples: 0.618618618619
weighted: 0.634352029679
Accuracy: 0.618618618619
Train ratio: 0.5
micro: 0.592548076923
macro: 0.476271952377
samples: 0.592548076923
weighted: 0.60087393748
Accuracy: 0.592548076923
Train ratio: 0.09999999999999998
micro: 0.514190317195
macro: 0.40189088656
samples: 0.514190317195
weighted: 0.524775054739
Accuracy: 0.514190317195

Run number 2:
Train ratio: 0.9
micro: 0.594594594595
macro: 0.45796027003
samples: 0.594594594595
weighted: 0.599856584083
Accuracy: 0.594594594595
Train ratio: 0.5
micro: 0.599759615385
macro: 0.476278259825
samples: 0.599759615385
weighted: 0.610340618199
Accuracy: 0.599759615385
Train ratio: 0.09999999999999998
micro: 0.513188647746
macro: 0.427385698593
samples: 0.513188647746
weighted: 0.519544471677
Accuracy: 0.513188647746

