In [1]:
#This file is to import two embeddings and merge them together to generate
# new set of embeddings

import numpy as np

data_location = './../generated_embedding/'
sec_embed = open(data_location+'citeseer.new_deewalk.embeddings','r')
first_embed = open(data_location+'citeseer.edges_struc2vec.embeddings','r')

In [2]:
#loading embedding files from deepwalk and struc2vec embeddings
#assumption embedding length is 128
import numpy as np
import pickle


#Read the first line and get number of nodes in the embedding
temp1 = first_embed.readline()
temp2 = sec_embed.readline()
temp1 = temp1.split()
temp2 = temp2.split()
num_node = int(temp1[0])
len_embed = int(temp1[1])

print("number of nodes %s and length of embedding is %s" % (num_node,len_embed))

new_arr = np.ndarray((num_node,2*len_embed),dtype=float)

#the code here loads each file in a line and then splits into list values.
#First value denotes the node number. That is used to get the index and other values are added to the
#array
for counter in range(num_node):
    temp_embed1 = first_embed.readline().split()
    index_one = int(temp_embed1[0])
    new_arr[index_one,:len_embed]=[float(i) for i in temp_embed1[1:]]
    
    temp_embed2 = sec_embed.readline().split()
    index_two = int(temp_embed2[0])
    new_arr[index_two,len_embed:] = [float(j) for j in temp_embed2[1:]]
    
'''

new_file = open(data_location+"citeseer_combined.embedding",'w')
for i in range(count):
    embed_one = first_embed.readline().split()
    embed_two = sec_embed.readline().split()
    combine = embed_one+embed_two[1:]
    combine = ' '.join(combine)
    new_file.write("%s\n" % combine)

'''
print("finished")

    
first_embed.close()
sec_embed.close()

number of nodes 3327 and length of embedding is 128
finished


In [5]:
#the above function seems to work but hard way to check for accuracy.
#So I will rewrite the code to add two variables and add them later.


def join_embedding(filename1,filename2):
    #loading embedding files from deepwalk and struc2vec embeddings
    #assumption embedding length is 128
    import numpy as np
    import pickle
    data_location = './../generated_embedding/'
    first_embed = open(data_location+filename1,'r')
    sec_embed = open(data_location+filename2,'r')


    #Read the first line and get number of nodes in the embedding
    temp1 = first_embed.readline()
    temp2 = sec_embed.readline()
    temp1 = temp1.split()
    temp2 = temp2.split()
    num_node = int(temp1[0])
    len_embed = int(temp1[1])

    print("number of nodes %s and length of embedding is %s" % (num_node,len_embed))

    temp_arr1 = np.ndarray((num_node,len_embed),dtype=float)
    temp_arr2 = np.ndarray((num_node,len_embed),dtype=float)
    new_arr1 = np.ndarray((num_node,2*len_embed),dtype=float)

    #the code here loads each file in a line and then splits into list values.
    #First value denotes the node number. That is used to get the index and other values are added to the
    #array
    for counter in range(num_node):
        temp_embed1 = first_embed.readline().split()
        index_one = int(temp_embed1[0])
        temp_arr1[index_one,:]=[float(i) for i in temp_embed1[1:]]
    
        temp_embed2 = sec_embed.readline().split()
        index_two = int(temp_embed2[0])
        temp_arr2[index_two,:] = [float(j) for j in temp_embed2[1:]]

    #combining two arrays to get one set of embeddings
    new_arr1[:,:len_embed] = temp_arr1[:,:]
    new_arr1[:,len_embed:] = temp_arr2[:,:]
    
    first_embed.close()
    sec_embed.close()
    print("finished")
    
    return new_arr1


In [ ]:
new_arr

In [7]:
from utils import run_embedding_classify_f1

In [ ]:
run_embedding_classify_f1('citeseer',new_arr,splits_ratio=[0.1, 0.5, 0.9])

In [15]:
#loading deepwalk embeddings for citeseer

f = open(data_location+'citeseer.edgelist_deepwalk.embeddings','r')

firstline = f.readline().split()
emb_node = int(firstline[0])
emb_len = int(firstline[1])

deepwalk_embed = np.ndarray((emb_node,emb_len),dtype=np.float32)

for i in range(emb_node):
    l = f.readline().split()
    t_arr = [float(j) for j in l[1:]]
    emb_index = int(l[0])
    deepwalk_embed[emb_index,:]=t_arr[:]
    
print("finished")
    


finished


In [12]:
 with open(data_location+'citeseer.new_deewalk.embeddings', 'rb') as efile:
        num_node, dim = map(int, efile.readline().split())
        emb_matrix = np.ndarray(shape=(num_node, dim), dtype=np.float32)
        for data in efile.readlines():
            node_id, *vector = data.split()
            node_id = int(node_id)
            emb_matrix[node_id, :] = np.array([i for i in map(np.float, vector)])
  


In [16]:
emb_matrix[0]

array([ 0.094527  , -0.013551  , -0.81741297, -0.095326  ,  0.440483  ,
        0.34503999, -0.204742  , -1.25870502,  0.131451  , -0.31465501,
        0.042019  , -0.056251  , -0.354498  ,  0.450371  , -0.084576  ,
       -0.036903  , -0.405341  , -0.48027301, -0.364216  , -0.200618  ,
        0.057037  ,  0.32684699,  0.26658899, -0.21323501,  0.441268  ,
        0.61049598, -1.75869298,  0.144767  , -0.11791   , -0.018084  ,
        0.0329    ,  0.33786201, -1.47459304, -1.34488201,  0.257934  ,
       -0.432152  , -0.037146  , -0.53013098,  1.30689204, -1.19934404,
       -1.00589502, -0.51819301,  0.355212  , -0.50352502, -0.39936799,
       -0.015843  , -0.72176802,  0.65939599, -0.717305  ,  0.51836199,
        0.91243201, -0.43010101,  0.410236  ,  0.42614701, -0.135993  ,
        0.94635999,  0.238647  ,  0.114305  , -0.18236101,  1.41709602,
        0.077559  , -0.28827199,  0.54010898, -0.97638202,  0.211916  ,
       -0.55612898, -0.61859697,  0.18791699,  0.25792301, -0.19

In [17]:
deepwalk_embed[0]

array([ 0.094527  , -0.013551  , -0.81741297, -0.095326  ,  0.440483  ,
        0.34503999, -0.204742  , -1.25870502,  0.131451  , -0.31465501,
        0.042019  , -0.056251  , -0.354498  ,  0.450371  , -0.084576  ,
       -0.036903  , -0.405341  , -0.48027301, -0.364216  , -0.200618  ,
        0.057037  ,  0.32684699,  0.26658899, -0.21323501,  0.441268  ,
        0.61049598, -1.75869298,  0.144767  , -0.11791   , -0.018084  ,
        0.0329    ,  0.33786201, -1.47459304, -1.34488201,  0.257934  ,
       -0.432152  , -0.037146  , -0.53013098,  1.30689204, -1.19934404,
       -1.00589502, -0.51819301,  0.355212  , -0.50352502, -0.39936799,
       -0.015843  , -0.72176802,  0.65939599, -0.717305  ,  0.51836199,
        0.91243201, -0.43010101,  0.410236  ,  0.42614701, -0.135993  ,
        0.94635999,  0.238647  ,  0.114305  , -0.18236101,  1.41709602,
        0.077559  , -0.28827199,  0.54010898, -0.97638202,  0.211916  ,
       -0.55612898, -0.61859697,  0.18791699,  0.25792301, -0.19

In [18]:
np.equal(deepwalk_embed[0],emb_matrix[0])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True]

In [13]:
#Deepwalk
run_embedding_classify_f1('citeseer',emb_matrix,splits_ratio=[0.1, 0.5, 0.9])

./../data/


C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricW

Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.618618618619
macro: 0.478295367306
samples: 0.618618618619
weighted: 0.634352029679
Accuracy: 0.618618618619
Train ratio: 0.5
micro: 0.592548076923
macro: 0.476271952377
samples: 0.592548076923
weighted: 0.60087393748
Accuracy: 0.592548076923
Train ratio: 0.09999999999999998
micro: 0.514190317195
macro: 0.40189088656
samples: 0.514190317195
weighted: 0.524775054739
Accuracy: 0.514190317195

Run number 2:
Train ratio: 0.9
micro: 0.594594594595
macro: 0.45796027003
samples: 0.594594594595
weighted: 0.599856584083
Accuracy: 0.594594594595
Train ratio: 0.5
micro: 0.599759615385
macro: 0.476278259825
samples: 0.599759615385
weighted: 0.610340618199
Accuracy: 0.599759615385
Train ratio: 0.09999999999999998
micro: 0.513188647746
macro: 0.427385698593
samples: 0.513188647746
weighted: 0.519544471677
Accuracy: 0.513188647746

Run number 3:
Train ratio: 0.9
micro: 0.573573573574
macro: 0.452099826591
samples: 0.57357357

In [10]:
#Deepwalk + Struc2vec combined
run_embedding_classify_f1('citeseer',new_arr,splits_ratio=[0.1, 0.5, 0.9])

./../data/


C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricW

Embedding dim: 256, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.567567567568
macro: 0.441948343812
samples: 0.567567567568
weighted: 0.579208161817
Accuracy: 0.567567567568
Train ratio: 0.5
micro: 0.557091346154
macro: 0.448913816824
samples: 0.557091346154
weighted: 0.563703745978
Accuracy: 0.557091346154
Train ratio: 0.09999999999999998
micro: 0.472787979967
macro: 0.371046000394
samples: 0.472787979967
weighted: 0.481680181878
Accuracy: 0.472787979967

Run number 2:
Train ratio: 0.9
micro: 0.615615615616
macro: 0.493907623061
samples: 0.615615615616
weighted: 0.62045327382
Accuracy: 0.615615615616
Train ratio: 0.5
micro: 0.5703125
macro: 0.455452056464
samples: 0.5703125
weighted: 0.577341893612
Accuracy: 0.5703125
Train ratio: 0.09999999999999998
micro: 0.484474123539
macro: 0.399524791528
samples: 0.484474123539
weighted: 0.492942048961
Accuracy: 0.484474123539

Run number 3:
Train ratio: 0.9
micro: 0.573573573574
macro: 0.450079025518
samples: 0.573573573574
weighted

In [11]:
from scipy import stats
temp_emb1 = stats.zscore(new_arr[:,:128])
print(temp_emb1.shape)
temp_emb2 = stats.zscore(new_arr[:,128:])
print(temp_emb2.shape)
new_temp_emb = np.concatenate((temp_emb1,temp_emb2),axis=1)
new_temp_emb.shape

(3327, 128)
(3327, 128)


(3327, 256)

In [12]:
run_embedding_classify_f1('citeseer',new_temp_emb,splits_ratio=[0.1, 0.5, 0.9])

./../data/


/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricW

Embedding dim: 256, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.555555555556
macro: 0.43922796047
samples: 0.555555555556
weighted: 0.562974719216
Accuracy: 0.555555555556
Train ratio: 0.5
micro: 0.529447115385
macro: 0.427875732745
samples: 0.529447115385
weighted: 0.532781039604
Accuracy: 0.529447115385
Train ratio: 0.09999999999999998
micro: 0.411686143573
macro: 0.326402868962
samples: 0.411686143573
weighted: 0.415121509161
Accuracy: 0.411686143573

Run number 2:
Train ratio: 0.9
micro: 0.591591591592
macro: 0.475105592338
samples: 0.591591591592
weighted: 0.595590767326
Accuracy: 0.591591591592
Train ratio: 0.5
micro: 0.530649038462
macro: 0.454765965657
samples: 0.530649038462
weighted: 0.534539605631
Accuracy: 0.530649038462
Train ratio: 0.09999999999999998
micro: 0.420367278798
macro: 0.349623276156
samples: 0.420367278798
weighted: 0.423928096567
Accuracy: 0.420367278798

Run number 3:
Train ratio: 0.9
micro: 0.561561561562
macro: 0.44147964786
samples: 0.5615615

In [3]:
new_arr.shape

(3327, 256)

In [5]:
import numpy as np
from sklearn.decomposition import PCA

In [7]:
pca = PCA(n_components=128)
data_transform = pca.fit_transform(new_arr)
data_transform.shape

(3327, 128)

In [9]:
run_embedding_classify_f1('citeseer',data_transform,splits_ratio=[0.1, 0.5, 0.9])

./../data/


C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricW

Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.57957957958
macro: 0.441373552466
samples: 0.57957957958
weighted: 0.594265754558
Accuracy: 0.57957957958
Train ratio: 0.5
micro: 0.566105769231
macro: 0.455978764383
samples: 0.566105769231
weighted: 0.573672038799
Accuracy: 0.566105769231
Train ratio: 0.09999999999999998
micro: 0.475125208681
macro: 0.370793668454
samples: 0.475125208681
weighted: 0.48648202256
Accuracy: 0.475125208681

Run number 2:
Train ratio: 0.9
micro: 0.597597597598
macro: 0.469345700557
samples: 0.597597597598
weighted: 0.602974643132
Accuracy: 0.597597597598
Train ratio: 0.5
micro: 0.576923076923
macro: 0.455247417435
samples: 0.576923076923
weighted: 0.587618116053
Accuracy: 0.576923076923
Train ratio: 0.09999999999999998
micro: 0.473789649416
macro: 0.38876406905
samples: 0.473789649416
weighted: 0.481967467235
Accuracy: 0.473789649416

Run number 3:
Train ratio: 0.9
micro: 0.57957957958
macro: 0.446398936566
samples: 0.57957957958

In [2]:
import networkx as nx


In [3]:
graph_location = './../data/'
g = nx.read_edgelist(graph_location+"citeseer.edges")

In [4]:
adj_mat = nx.to_numpy_matrix(g)
adj_mat.shape

(3327, 3327)

In [6]:
pca = PCA(n_components=128)
data_transform = pca.fit_transform(adj_mat)
data_transform.shape

(3327, 128)

In [8]:
run_embedding_classify_f1('citeseer',data_transform,splits_ratio=[0.1, 0.5, 0.9])

./../data/


C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricW

Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.174174174174
macro: 0.111687481317
samples: 0.174174174174
weighted: 0.203786395091
Accuracy: 0.174174174174
Train ratio: 0.5
micro: 0.191105769231
macro: 0.113778848918
samples: 0.191105769231
weighted: 0.232704319557
Accuracy: 0.191105769231
Train ratio: 0.09999999999999998
micro: 0.19632721202
macro: 0.115893142539
samples: 0.19632721202
weighted: 0.237220402746
Accuracy: 0.19632721202

Run number 2:
Train ratio: 0.9
micro: 0.192192192192
macro: 0.113572636951
samples: 0.192192192192
weighted: 0.239718459786
Accuracy: 0.192192192192
Train ratio: 0.5
micro: 0.202524038462
macro: 0.122506914012
samples: 0.202524038462
weighted: 0.244802847519
Accuracy: 0.202524038462
Train ratio: 0.09999999999999998
micro: 0.194991652755
macro: 0.0880890024583
samples: 0.194991652755
weighted: 0.270665934654
Accuracy: 0.194991652755

Run number 3:
Train ratio: 0.9
micro: 0.162162162162
macro: 0.0983468949902
samples: 0.162162

C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [9]:
adj_mat[0,:]

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [10]:
data_transform[0,:]

array([ -4.37248194e-02,   1.35351087e-02,  -2.45979142e-03,
        -4.27657802e-03,  -1.46511699e-02,  -2.81964097e-02,
         4.03900167e-04,   8.61116118e-03,  -1.19565004e-03,
        -2.39239879e-03,  -5.48842994e-03,  -3.93353297e-03,
        -1.19923333e-02,   7.36832386e-03,  -6.04236579e-04,
         7.51365259e-04,  -7.72837871e-03,  -7.15928461e-03,
        -5.85094392e-03,  -5.14874306e-03,   1.12996806e-03,
        -2.96949833e-03,  -4.59418482e-03,  -4.61579532e-03,
        -1.62605672e-02,  -4.15038456e-03,   1.42923708e-03,
         1.23921627e-03,  -3.41254018e-03,   2.77734385e-03,
        -5.97983373e-03,   3.05494117e-04,   5.89126240e-04,
        -7.89385887e-04,   1.53020081e-03,  -7.11374982e-03,
        -5.34117983e-03,   1.40815817e-03,  -1.14849790e-03,
         8.00558625e-04,   2.07831479e-04,  -9.02471543e-03,
        -5.32129709e-03,   7.28588819e-04,   3.20453416e-03,
        -4.51006355e-03,  -1.13881465e-03,   2.36125846e-04,
        -3.87957401e-04,