In [1]:
#This file is to import two embeddings and merge them together to generate
# new set of embeddings

import numpy as np

data_location = './../generated_embedding/'
sec_embed = open(data_location+'citeseer.new_deewalk.embeddings','r')
first_embed = open(data_location+'citeseer.edges_struc2vec.embeddings','r')

In [2]:
#loading embedding files from deepwalk and struc2vec embeddings
#assumption embedding length is 128
import numpy as np
import pickle


#Read the first line and get number of nodes in the embedding
temp1 = first_embed.readline()
temp2 = sec_embed.readline()
temp1 = temp1.split()
temp2 = temp2.split()
num_node = int(temp1[0])
len_embed = int(temp1[1])

print("number of nodes %s and length of embedding is %s" % (num_node,len_embed))

new_arr = np.ndarray((num_node,2*len_embed),dtype=float)

#the code here loads each file in a line and then splits into list values.
#First value denotes the node number. That is used to get the index and other values are added to the
#array
for counter in range(num_node):
    temp_embed1 = first_embed.readline().split()
    index_one = int(temp_embed1[0])
    new_arr[index_one,:len_embed]=[float(i) for i in temp_embed1[1:]]
    
    temp_embed2 = sec_embed.readline().split()
    index_two = int(temp_embed2[0])
    new_arr[index_two,len_embed:] = [float(j) for j in temp_embed2[1:]]
    
'''

new_file = open(data_location+"citeseer_combined.embedding",'w')
for i in range(count):
    embed_one = first_embed.readline().split()
    embed_two = sec_embed.readline().split()
    combine = embed_one+embed_two[1:]
    combine = ' '.join(combine)
    new_file.write("%s\n" % combine)

'''
print("finished")

    
first_embed.close()
sec_embed.close()

number of nodes 3327 and length of embedding is 128
finished


In [5]:
#the above function seems to work but hard way to check for accuracy.
#So I will rewrite the code to add two variables and add them later.


def join_embedding(filename1,filename2):
    #loading embedding files from deepwalk and struc2vec embeddings
    #assumption embedding length is 128
    import numpy as np
    import pickle
    data_location = './../generated_embedding/'
    first_embed = open(data_location+filename1,'r')
    sec_embed = open(data_location+filename2,'r')


    #Read the first line and get number of nodes in the embedding
    temp1 = first_embed.readline()
    temp2 = sec_embed.readline()
    temp1 = temp1.split()
    temp2 = temp2.split()
    num_node = int(temp1[0])
    len_embed = int(temp1[1])

    print("number of nodes %s and length of embedding is %s" % (num_node,len_embed))

    temp_arr1 = np.ndarray((num_node,len_embed),dtype=float)
    temp_arr2 = np.ndarray((num_node,len_embed),dtype=float)
    new_arr1 = np.ndarray((num_node,2*len_embed),dtype=float)

    #the code here loads each file in a line and then splits into list values.
    #First value denotes the node number. That is used to get the index and other values are added to the
    #array
    for counter in range(num_node):
        temp_embed1 = first_embed.readline().split()
        index_one = int(temp_embed1[0])
        temp_arr1[index_one,:]=[float(i) for i in temp_embed1[1:]]
    
        temp_embed2 = sec_embed.readline().split()
        index_two = int(temp_embed2[0])
        temp_arr2[index_two,:] = [float(j) for j in temp_embed2[1:]]

    #combining two arrays to get one set of embeddings
    new_arr1[:,:len_embed] = temp_arr1[:,:]
    new_arr1[:,len_embed:] = temp_arr2[:,:]
    
    first_embed.close()
    sec_embed.close()
    print("finished")
    
    return new_arr1


In [3]:
from utils import run_embedding_classify_f1

In [ ]:
run_embedding_classify_f1('citeseer',new_arr,splits_ratio=[0.1, 0.5, 0.9])

In [15]:
#loading deepwalk embeddings for citeseer

f = open(data_location+'citeseer.edgelist_deepwalk.embeddings','r')

firstline = f.readline().split()
emb_node = int(firstline[0])
emb_len = int(firstline[1])

deepwalk_embed = np.ndarray((emb_node,emb_len),dtype=np.float32)

for i in range(emb_node):
    l = f.readline().split()
    t_arr = [float(j) for j in l[1:]]
    emb_index = int(l[0])
    deepwalk_embed[emb_index,:]=t_arr[:]
    
print("finished")
    


finished


In [4]:
 with open(data_location+'citeseer.new_deewalk.embeddings', 'rb') as efile:
        num_node, dim = map(int, efile.readline().split())
        emb_matrix = np.ndarray(shape=(num_node, dim), dtype=np.float32)
        for data in efile.readlines():
            node_id, *vector = data.split()
            node_id = int(node_id)
            emb_matrix[node_id, :] = np.array([i for i in map(np.float, vector)])
  


In [16]:
emb_matrix[0]

array([ 0.094527  , -0.013551  , -0.81741297, -0.095326  ,  0.440483  ,
        0.34503999, -0.204742  , -1.25870502,  0.131451  , -0.31465501,
        0.042019  , -0.056251  , -0.354498  ,  0.450371  , -0.084576  ,
       -0.036903  , -0.405341  , -0.48027301, -0.364216  , -0.200618  ,
        0.057037  ,  0.32684699,  0.26658899, -0.21323501,  0.441268  ,
        0.61049598, -1.75869298,  0.144767  , -0.11791   , -0.018084  ,
        0.0329    ,  0.33786201, -1.47459304, -1.34488201,  0.257934  ,
       -0.432152  , -0.037146  , -0.53013098,  1.30689204, -1.19934404,
       -1.00589502, -0.51819301,  0.355212  , -0.50352502, -0.39936799,
       -0.015843  , -0.72176802,  0.65939599, -0.717305  ,  0.51836199,
        0.91243201, -0.43010101,  0.410236  ,  0.42614701, -0.135993  ,
        0.94635999,  0.238647  ,  0.114305  , -0.18236101,  1.41709602,
        0.077559  , -0.28827199,  0.54010898, -0.97638202,  0.211916  ,
       -0.55612898, -0.61859697,  0.18791699,  0.25792301, -0.19

In [17]:
deepwalk_embed[0]

array([ 0.094527  , -0.013551  , -0.81741297, -0.095326  ,  0.440483  ,
        0.34503999, -0.204742  , -1.25870502,  0.131451  , -0.31465501,
        0.042019  , -0.056251  , -0.354498  ,  0.450371  , -0.084576  ,
       -0.036903  , -0.405341  , -0.48027301, -0.364216  , -0.200618  ,
        0.057037  ,  0.32684699,  0.26658899, -0.21323501,  0.441268  ,
        0.61049598, -1.75869298,  0.144767  , -0.11791   , -0.018084  ,
        0.0329    ,  0.33786201, -1.47459304, -1.34488201,  0.257934  ,
       -0.432152  , -0.037146  , -0.53013098,  1.30689204, -1.19934404,
       -1.00589502, -0.51819301,  0.355212  , -0.50352502, -0.39936799,
       -0.015843  , -0.72176802,  0.65939599, -0.717305  ,  0.51836199,
        0.91243201, -0.43010101,  0.410236  ,  0.42614701, -0.135993  ,
        0.94635999,  0.238647  ,  0.114305  , -0.18236101,  1.41709602,
        0.077559  , -0.28827199,  0.54010898, -0.97638202,  0.211916  ,
       -0.55612898, -0.61859697,  0.18791699,  0.25792301, -0.19

In [18]:
np.equal(deepwalk_embed[0],emb_matrix[0])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True]

In [6]:
#Deepwalk
run_embedding_classify_f1('citeseer',emb_matrix,splits_ratio=[0.9])

./../data/
file saved
Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.09999999999999998
micro: 0.514190317195
macro: 0.40189088656
samples: 0.514190317195
weighted: 0.524775054739
Accuracy: 0.514190317195



/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [7]:
#Deepwalk + Struc2vec combined
run_embedding_classify_f1('citeseer',new_arr,splits_ratio=[0.9])

./../data/
file saved
Embedding dim: 256, graph: citeseer

Run number 1:
Train ratio: 0.09999999999999998
micro: 0.472787979967
macro: 0.371046000394
samples: 0.472787979967
weighted: 0.481680181878
Accuracy: 0.472787979967



/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [11]:
from scipy import stats
temp_emb1 = stats.zscore(new_arr[:,:128])
print(temp_emb1.shape)
temp_emb2 = stats.zscore(new_arr[:,128:])
print(temp_emb2.shape)
new_temp_emb = np.concatenate((temp_emb1,temp_emb2),axis=1)
new_temp_emb.shape

(3327, 128)
(3327, 128)


(3327, 256)

In [12]:
run_embedding_classify_f1('citeseer',new_temp_emb,splits_ratio=[0.1, 0.5, 0.9])

./../data/


/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/sunil/anaconda3/envs/env1/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricW

Embedding dim: 256, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.555555555556
macro: 0.43922796047
samples: 0.555555555556
weighted: 0.562974719216
Accuracy: 0.555555555556
Train ratio: 0.5
micro: 0.529447115385
macro: 0.427875732745
samples: 0.529447115385
weighted: 0.532781039604
Accuracy: 0.529447115385
Train ratio: 0.09999999999999998
micro: 0.411686143573
macro: 0.326402868962
samples: 0.411686143573
weighted: 0.415121509161
Accuracy: 0.411686143573

Run number 2:
Train ratio: 0.9
micro: 0.591591591592
macro: 0.475105592338
samples: 0.591591591592
weighted: 0.595590767326
Accuracy: 0.591591591592
Train ratio: 0.5
micro: 0.530649038462
macro: 0.454765965657
samples: 0.530649038462
weighted: 0.534539605631
Accuracy: 0.530649038462
Train ratio: 0.09999999999999998
micro: 0.420367278798
macro: 0.349623276156
samples: 0.420367278798
weighted: 0.423928096567
Accuracy: 0.420367278798

Run number 3:
Train ratio: 0.9
micro: 0.561561561562
macro: 0.44147964786
samples: 0.5615615

In [3]:
new_arr.shape

(3327, 256)

In [5]:
import numpy as np
from sklearn.decomposition import PCA

In [7]:
pca = PCA(n_components=128)
data_transform = pca.fit_transform(new_arr)
data_transform.shape

(3327, 128)

In [9]:
run_embedding_classify_f1('citeseer',data_transform,splits_ratio=[0.1, 0.5, 0.9])

./../data/


C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricW

Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.57957957958
macro: 0.441373552466
samples: 0.57957957958
weighted: 0.594265754558
Accuracy: 0.57957957958
Train ratio: 0.5
micro: 0.566105769231
macro: 0.455978764383
samples: 0.566105769231
weighted: 0.573672038799
Accuracy: 0.566105769231
Train ratio: 0.09999999999999998
micro: 0.475125208681
macro: 0.370793668454
samples: 0.475125208681
weighted: 0.48648202256
Accuracy: 0.475125208681

Run number 2:
Train ratio: 0.9
micro: 0.597597597598
macro: 0.469345700557
samples: 0.597597597598
weighted: 0.602974643132
Accuracy: 0.597597597598
Train ratio: 0.5
micro: 0.576923076923
macro: 0.455247417435
samples: 0.576923076923
weighted: 0.587618116053
Accuracy: 0.576923076923
Train ratio: 0.09999999999999998
micro: 0.473789649416
macro: 0.38876406905
samples: 0.473789649416
weighted: 0.481967467235
Accuracy: 0.473789649416

Run number 3:
Train ratio: 0.9
micro: 0.57957957958
macro: 0.446398936566
samples: 0.57957957958

In [1]:
import networkx as nx


In [2]:
graph_location = './../data/'
g = nx.read_edgelist(graph_location+"citeseer.edges")

In [4]:
adj_mat = nx.to_numpy_matrix(g)
adj_mat.shape

(3327, 3327)

In [6]:
pca = PCA(n_components=128)
data_transform = pca.fit_transform(adj_mat)
data_transform.shape

(3327, 128)

In [8]:
#running with embedding reduced with pca transform
run_embedding_classify_f1('citeseer',data_transform,splits_ratio=[0.1, 0.5, 0.9])

./../data/


C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\multiclass.py:76: UserWarning: Label not 0 is present in all training examples.
  str(classes[c]))
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricW

Embedding dim: 128, graph: citeseer

Run number 1:
Train ratio: 0.9
micro: 0.174174174174
macro: 0.111687481317
samples: 0.174174174174
weighted: 0.203786395091
Accuracy: 0.174174174174
Train ratio: 0.5
micro: 0.191105769231
macro: 0.113778848918
samples: 0.191105769231
weighted: 0.232704319557
Accuracy: 0.191105769231
Train ratio: 0.09999999999999998
micro: 0.19632721202
macro: 0.115893142539
samples: 0.19632721202
weighted: 0.237220402746
Accuracy: 0.19632721202

Run number 2:
Train ratio: 0.9
micro: 0.192192192192
macro: 0.113572636951
samples: 0.192192192192
weighted: 0.239718459786
Accuracy: 0.192192192192
Train ratio: 0.5
micro: 0.202524038462
macro: 0.122506914012
samples: 0.202524038462
weighted: 0.244802847519
Accuracy: 0.202524038462
Train ratio: 0.09999999999999998
micro: 0.194991652755
macro: 0.0880890024583
samples: 0.194991652755
weighted: 0.270665934654
Accuracy: 0.194991652755

Run number 3:
Train ratio: 0.9
micro: 0.162162162162
macro: 0.0983468949902
samples: 0.162162

C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Program Files\Anaconda3\envs\secenv3.5\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [9]:
adj_mat[0,:]

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [4]:
#This part is to test what's wrong with the prediction
#and analyze which node labels get assigned wrong in the prediction task

import pickle
from prettytable import PrettyTable

# this is for just deepwalk embedding 

with open('stats_128.pickle','rb') as f_emb:
    emb1_indices,emb1_predict,emb1_label = pickle.load(f_emb)
    
f_emb.close()

In [5]:
print(emb1_indices.shape)
print(emb1_predict.shape)
print(emb1_label.shape)

(2995,)
(2995, 7)
(2995, 7)


In [25]:
#This is to check the number of instances that were wrongly predicted
counter = 0
for i in range(2995):
    if (np.array_equal(emb1_predict[i,:],emb1_label[i,:]))== False:
        counter = counter + 1
        
print(counter)

1455


In [34]:
table = PrettyTable(['Serial No.','Node no.','True Label','Predicted Label','Degree'])
counter = 0
for i in range(2995):
    if (np.array_equal(emb1_predict[i,:],emb1_label[i,:]))== False:
        counter = counter + 1
        table.add_row([counter,str(emb1_indices[i]),np.nonzero(emb1_label[i,:]),np.nonzero(emb1_predict[i,:]),g.degree(str(emb1_indices[i]))])
        
print(table)
        

+------------+----------+---------------+-----------------+--------+
| Serial No. | Node no. |   True Label  | Predicted Label | Degree |
+------------+----------+---------------+-----------------+--------+
|     1      |   2168   | (array([6]),) |  (array([5]),)  |   1    |
|     2      |   2878   | (array([5]),) |  (array([6]),)  |   2    |
|     3      |   1739   | (array([5]),) |  (array([3]),)  |   1    |
|     4      |   2698   | (array([2]),) |  (array([3]),)  |   2    |
|     5      |   1138   | (array([5]),) |  (array([3]),)  |   1    |
|     6      |   2409   | (array([1]),) |  (array([4]),)  |   1    |
|     7      |   2209   | (array([2]),) |  (array([4]),)  |   1    |
|     8      |   3233   | (array([6]),) |  (array([3]),)  |   1    |
|     9      |    22    | (array([1]),) |  (array([3]),)  |   1    |
|     10     |   2466   | (array([1]),) |  (array([5]),)  |   1    |
|     11     |   1412   | (array([2]),) |  (array([1]),)  |   1    |
|     12     |   2769   | (array([

In [3]:
#this is for the combined approach 
#everything from before together in single cell

import pickle
from prettytable import PrettyTable

# this is for just deepwalk embedding 

with open('stats_256.pickle','rb') as f_emb:
    emb2_indices,emb2_predict,emb2_label = pickle.load(f_emb)
    
f_emb.close()

table1 = PrettyTable(['Serial No.','Node no.','True Label','Predicted Label','Degree'])
counter = 0
for i in range(2995):
    if (np.array_equal(emb2_predict[i,:],emb2_label[i,:]))== False:
        counter = counter + 1
        table1.add_row([counter,str(emb2_indices[i]),np.nonzero(emb2_label[i,:]),np.nonzero(emb2_predict[i,:]),g.degree(str(emb2_indices[i]))])
        
print(table)

ModuleNotFoundError: No module named 'prettytable'

In [17]:
g.neighbors("2466")

['2420']

In [18]:
import numpy as np
np.where(emb1_indices==2420)

(array([872]),)

In [20]:
ind = 872
print(emb1_indices[ind])
print(emb1_label[ind])
print(emb1_predict[ind])

2420
[0 1 0 0 0 0 0]
[ 0.  0.  0.  0.  0.  1.  0.]


In [10]:
emb1_label

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [11]:
emb1_predict

array([[ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.]])

In [22]:
#this code will count the number of nodes with particualr degree
#to check what type of nodes usually give wrong results

#reusing the code from above and storing the count in dictionary
#assuming the arrays have been loaded already
counts = dict()
for i in range(2995):
    if (np.array_equal(emb1_predict[i,:],emb1_label[i,:]))== False:
        degree = g.degree(str(emb1_indices[i]))
        counts[degree] = counts.get(degree,0)+1
       
        


In [23]:
counts

{1: 725,
 2: 347,
 3: 171,
 4: 81,
 5: 43,
 6: 35,
 7: 19,
 8: 7,
 9: 10,
 10: 3,
 11: 6,
 12: 3,
 13: 1,
 15: 1,
 16: 1,
 18: 1,
 19: 1}

In [24]:
#same stuff for all nodes

counts_1 = dict()
for i in range(2995):
    degree = g.degree(str(emb1_indices[i]))
    counts_1[degree] = counts_1.get(degree,0)+1

{1: 1169,
 2: 736,
 3: 421,
 4: 214,
 5: 134,
 6: 106,
 7: 59,
 8: 32,
 9: 23,
 10: 27,
 11: 14,
 12: 17,
 13: 4,
 14: 2,
 15: 9,
 16: 7,
 17: 3,
 18: 2,
 19: 3,
 20: 1,
 21: 2,
 23: 2,
 27: 1,
 28: 1,
 29: 1,
 30: 1,
 34: 1,
 35: 1,
 51: 1,
 99: 1}

In [41]:
for i in list(range(1,14)):
    print("for "+str(i)+" total: "+str(counts_1[i])+" and wrong prediction: "+ str(counts[i])+"("+str(int(counts[i]/counts_1[i]*100))+"%)")

for 1 total: 1169 and wrong prediction: 725(62%)
for 2 total: 736 and wrong prediction: 347(47%)
for 3 total: 421 and wrong prediction: 171(40%)
for 4 total: 214 and wrong prediction: 81(37%)
for 5 total: 134 and wrong prediction: 43(32%)
for 6 total: 106 and wrong prediction: 35(33%)
for 7 total: 59 and wrong prediction: 19(32%)
for 8 total: 32 and wrong prediction: 7(21%)
for 9 total: 23 and wrong prediction: 10(43%)
for 10 total: 27 and wrong prediction: 3(11%)
for 11 total: 14 and wrong prediction: 6(42%)
for 12 total: 17 and wrong prediction: 3(17%)
for 13 total: 4 and wrong prediction: 1(25%)


In [43]:
np.array_equal(emb1_predict,emb2_predict)

False

In [48]:
count = 0
for i in range(len(emb1_predict)):
    if not(np.array_equal(emb1_predict[i,:],emb2_predict[i,:])):
        count +=1
print(count)

583


In [45]:
emb1_predict[3]

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.])